### ISSUE TITLE
Path rendering issues when "arcTo" command is used

### ISSUE THREAD

**Issue by zpl-zak** [tdewolff/canvas#309] opened 2024-07-24 07:29 UTC
Hey,

we've updated to the latest commit recently, but unfortunately noticed a regression in path rendering code, namely the arcTo command.

The following SVG example demonstrates the issue where nodes render incorrectly:

![paths](https://github.com/user-attachments/assets/c965e6dd-3758-451d-bc13-6de0a4a3e4d3)

This is the original SVG file we tried to render:

![paths](https://github.com/user-attachments/assets/cd4bf007-18ed-401d-81b1-ac8c80d0a908)

You can use the following snippet to reproduce this issue:
```go
package main

import (
	"log"
	"os"

	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers"
)

func main() {
	// Read the SVG file
	svgFile, err := os.Open("paths.svg")
	if err != nil {
		log.Fatalf("Error opening SVG file: %v", err)
	}
	defer svgFile.Close()

	// Load the SVG content
	paths, err := canvas.ParseSVG(svgFile)
	if err != nil {
		log.Fatalf("Error parsing SVG: %v", err)
	}

	if err := renderers.Write("paths.png", paths, canvas.DPMM(6.4)); err != nil {
		panic(err)
	}
}

```

**Comment by tdewolff** [comment] 2024-10-24 16:19
Sorry for the very late reply, this seems to be an issue with the path intersection code, specifically after "settling" the stroked path if I remember correctly (I had looked at this bug some months ago). This is being actively worked on and this particular case already works in my local repository. I'm expecting a fix in November.

**Comment by tdewolff** [comment] 2024-11-03 15:03
This should now be fixed with the new (much improved) implementation, see https://github.com/tdewolff/canvas/wiki/Boolean-operations for more information. Most noteworthy is that all tests now finally work, and that I've already seen an improvement of 20x in speed for a typical path. Please re-open new issues if you encounter bugs.

I've confirmed that the output is not identical to the one you posted.

**Closed by tdewolff** 2024-11-03 15:03 UTC
