### ISSUE TITLE
I just want to read the svg and save it directly as a new svg, but its Y axis direction is reversed

### ISSUE THREAD

**Issue by shuqingzai** [tdewolff/canvas#195] opened 2023-02-21 09:14 UTC
source

```xml
<svg id="图层_1" data-name="图层 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 5342 499"><defs><style>.cls-1{fill:#eee;}</style></defs><title>平铺区域10张</title><path class="cls-1" d="M5342,100.6V484.4a14.6,14.6,0,0,1-14.6,14.6H0V59.19A59.19,59.19,0,0,1,59.19,0H279.81A59.19,59.19,0,0,1,339,59.19V80a6,6,0,0,0,6,6H5327.4A14.6,14.6,0,0,1,5342,100.6Z"/></svg>
```

**Comment by tdewolff** [comment] 2023-03-15 01:06
Duplicate of #192

**Closed by tdewolff** 2023-03-15 01:06 UTC
