### ISSUE TITLE
Bug found in path intersection code

### ISSUE THREAD

**Issue by farhaven** [tdewolff/canvas#287] opened 2024-04-10 14:23 UTC
Hi!

We're currently upgrading our dependency on `canvas` from commit `3711dfc3bb35` to `2f948bde1ebd`, and one of our tests fails with the following panic:

```
panic: Bug found in path intersection code, please report on GitHub at https://github.com/tdewolff/canvas/issues with the path or paths that caused this panic. 

goroutine 16 [running]:
testing.tRunner.func1.2({0x104f82240, 0x10513ea40})
	GOROOT/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1634 +0x33c
panic({0x104f82240?, 0x10513ea40?})
	GOROOT/src/runtime/panic.go:770 +0x124
github.com/tdewolff/canvas.pathIntersections(0x14002768b88, 0x14002768b88, 0x0, 0x0)
	external/com_github_tdewolff_canvas/path_intersection_util.go:614 +0x2f30
github.com/tdewolff/canvas.(*Path).Settle(0x14002768b88, 0x2)
	external/com_github_tdewolff_canvas/path_intersection.go:167 +0x398
github.com/tdewolff/canvas.(*Path).Stroke(0x1400000f170, 0x3fc999999999999a, {0x1051417e0, 0x1059ccb20}, {0x105141760, 0x1058fc840}, 0x3f8156f8c384071a)
	external/com_github_tdewolff_canvas/path_stroke.go:613 +0x260
github.com/tdewolff/canvas/renderers/rasterizer.(*Rasterizer).RenderPath(0x14002788000, 0x140026fe840, {{{0x0, 0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, ...}, ...)
	external/com_github_tdewolff_canvas/renderers/rasterizer/rasterizer.go:84 +0x1a0
github.com/tdewolff/canvas.(*Canvas).RenderViewTo(0x1400007eba0, {0x10514e0e0, 0x14002788000}, {{0x3ff0000000000000, 0x0, 0x0}, {0x0, 0x3ff0000000000000, 0x0}})
	external/com_github_tdewolff_canvas/canvas.go:856 +0x294
github.com/tdewolff/canvas.(*Canvas).RenderTo(0x1400007eba0, {0x10514e0e0, 0x14002788000})
	external/com_github_tdewolff_canvas/canvas.go:841 +0x58

[... local part of stack trace censored ...]

testing.tRunner(0x1400065c340, 0x14002434080)
	GOROOT/src/testing/testing.go:1689 +0xec
created by testing.(*T).Run in goroutine 24
	GOROOT/src/testing/testing.go:1742 +0x318
```

The path seems to be this:

```
Path: len=9 data=M-0.1997406229376793 296.9999999925494L-0.1997406229376793 158.88740153238177L-0.19974062293732664 158.8874019079834L-0.19999999999964735 20.77454766193328L0.19999999999964735 20.774546910730027L0.20025937706232075 158.88740134458095L0.20025937706232072 158.88740153238177L0.20025937706232072 296.9999999925494z
Intersection 0: seg=(1,2) t=(0.9999999972804681,1) pos=(-0.19974062293732664,158.8874019079834) dir=(270°,89.99994620346916°) tangent
Intersection 1: seg=(1,3) t=(0.9999999986401219,1.359651237533596e-09) pos=(-0.1997406229376793,158.88740172019808) dir=(270°,269.9998923980606°)
Intersection 2: seg=(2,3) t=(0,2.7195268509761408e-09) pos=(-0.1997406229376793,158.88740153238177) dir=(89.99994620346916°,269.9998923980606°) tangent
```

I'll try to reduce this down to a standalone test case, and will update this issue once I have created one.

**Comment by tdewolff** [comment] 2024-04-10 15:38
Thank you Gregor for the report. This is a problem when resolving self-intersections of a path by "settling" (resolving or simplifying) it after applying stroke.

It looks like the stroke of an (almost) straight path and the problem appear numerical. Specifically, when checking the self-intersections in a path, it should remove the connections at the endpoints between consecutive line segments (since they always touch), but it doesn't appear to remove them in this case.

You have three line segments involved:
```
-0.1997406229376793 296.9999999925494 => -0.1997406229376793 158.88740153238177
 -0.1997406229376793 158.88740153238177 => -0.19974062293732664 158.8874019079834
-0.19974062293732664 158.8874019079834 => -0.19999999999964735 20.77454766193328
```

As you can see, the second line segment is of length 4e-7, this is still bigger than Epsilon (=1e-9 if I'm not mistaken), so I'm unsure why this is causing a problem. This may be a problem in the line-line intersection code w.r.t. numerical floating point problems. Will look into this.

**Comment by tdewolff** [comment] 2024-04-15 00:53
I see, the problem is not so much in eliminating line-line intersections for self intersecting paths, it's that there is a numerical precision error for almost linear/parallel/overlapping lines. The commit seems to fix this issue, can you please check if it works?

**Comment by farhaven** [comment] 2024-04-15 07:29
The commit fixed the particular path in the initial report, now the test progresses a bit further to this one:

```
Path: len=9 data=M162.43449681368278 -9.999996185876773L162.43449681368278 -9.99998551284069L162.2344968136828 -9.999985512840697L162.23449681368282 -10.399974839804614L162.4344968136828 -10.3999748398046L162.43449681368278 -9.999985512840682L162.2344968136828 -9.99998551284069L162.2344968136828 -9.999996185876773z
Intersection 0: seg=(1,5) t=(0,0.9999733166977942) pos=(162.43449681368278,-9.999996185876773) dir=(90°,90.00000000000408°) tangent
Intersection 1: seg=(1,5) t=(1,0.9999999999999822) pos=(162.43449681368278,-9.99998551284069) dir=(90°,90.00000000000408°) tangent
Intersection 2: seg=(2,5) t=(0,0.9999999999999821) pos=(162.43449681368278,-9.99998551284069) dir=(180.00000000000202°,90.00000000000408°) tangent
Intersection 3: seg=(2,6) t=(0,0) pos=(162.43449681368278,-9.99998551284069) dir=(180.00000000000202°,180.00000000000202°) tangent
Intersection 4: seg=(2,6) t=(1,1) pos=(162.2344968136828,-9.999985512840697) dir=(180.00000000000202°,180.00000000000202°) tangent
Intersection 5: seg=(3,6) t=(0,1) pos=(162.2344968136828,-9.99998551284069) dir=(270.0000000000041°,180.00000000000202°) tangent
Intersection 6: seg=(3,7) t=(0,0) pos=(162.2344968136828,-9.99998551284069) dir=(270.0000000000041°,270°) tangent
Intersection 7: seg=(2,7) t=(1,6.657362817941556e-10) pos=(162.2344968136828,-9.999985512840697) dir=(180.00000000000202°,270°) tangent
Intersection 8: seg=(3,7) t=(2.6683302170291398e-05,1) pos=(162.2344968136828,-9.999996185876773) dir=(270.0000000000041°,270°) tangent
Intersection 9: seg=(3,8) t=(2.6683302170291398e-05,3.791925304638669e-18) pos=(162.23449681368282,-9.999996185876773) dir=(270.0000000000041°,0°) tangent
Intersection 10: seg=(5,8) t=(0.9999733166977942,1) pos=(162.43449681368278,-9.999996185876773) dir=(90.00000000000408°,0°) tangent
```

I haven't gotten around to packaging up our test case into a standalone thing, I'll do that ASAP.

**Comment by farhaven** [comment] 2024-04-15 07:38
FWIW, I get test failures when I run `go test ./...` on the `main` branch of this package, all of which look like the result of floating point inaccuracies.

I run my tests on an ARM64 macbook, and for our own code base we had to introduce some "fuzzyness" that we tolerate in test results because on ARM64 the Go compiler does automatic FMA fusing, but it doesn't do that on x86_64 (where our CI/production systems run).

Maybe something similar would be appropriate here as well?

**Comment by tdewolff** [comment] 2024-04-15 12:34
Hi Gregor, thanks I'll take a look. Regarding the failing tests, there are many tests failing as they are outstanding bugs. I'm trying as much as I can to fix bugs that bother people, but there is still significant work left to fix all edge-cases, and until I have the time to do so, new bug reports will keep appearing hehe.

I didn't know about FMA fusing, thanks for that. I do check for floating point intervals, not exact values, so not sure if it is such a big problem? As I said, the tests fail as there are many outstanding bugs (and there are many commented tests that fail too) unfortunately :-(

**Comment by farhaven** [comment] 2024-04-15 15:14
Yeah, FMA is probably not the main problem here, you're right.

FWIW, I do appreciate your quick reaction to issue reports a lot, but by all means don't feel pressured to work on stuff just on my (resp. my employers) behalf. We're extremely grateful for the canvas package as it is already :)

I'll try and see if I can figure out what's wrong with out test case tomorrow over the day, maybe this is a "many eyeballs make all bugs shallow" thing :)

**Comment by tdewolff** [comment] 2024-04-15 21:20
Thanks Gregor. What is your use-case?

The paths you've shown so far are quite "pathological" in the sense that they seem to be the result of something that generates suboptimal paths. The last case you sent for example, is a simple rectangle when viewing as SVG. It has however a small triangle cut out at the bottom. Would it make sense to first "clean-up" the path before applying stroke? I always meant to implement the [Ramer–Douglas–Peucker algorithm](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm), but haven't come around yet.

**Comment by farhaven** [comment] 2024-04-16 07:51
Our use case is plotting geographical surveys after projecting them, so cleaning up polygons is sadly not possible (because they represent real measured geographical features).

The process in general is that a user walks around with a GPS (or other GNSS) receiver and marks off positions on a construction site to track utility hookups, power/gas/water lines, etc...

We then project the measured points (which are in S^2) onto R^2, construct a set of additional lines that indicate things like "distance of this point from a vanishing line" and "distance from orthogonal of the vanishing line", resize and scale the whole thing to fit on, say, a sheet of A4 paper, and use the canvas package to render the whole thing.

The paths in my posts are all from the same test case, which admittedly is a constructed case of a smiley face, but one that could conveivably be constructed by walking across a field and marking off points.

**Comment by tdewolff** [comment] 2024-04-18 21:13
I'm working to use this library for a very similar purpose, so better get this fixed! What ground resolution do you need? For example, if you are good with meter precision, or maybe centimeter precision, you could round all numbers to that precision first.

This bug in particular doesn't find an intersection between the end of the first line segment, and the start of the 6th line segment (position `{162.4344968,-9.999985513}`), due to numerical issues in the line-line intersection test (again). Trying to work on a better solution.

**Comment by tdewolff** [comment] 2024-04-19 00:05
I've fixed part of the bug, but the `Settle` function outputs a bad path.

**Closed** 2024-04-19 14:53 UTC
