### ISSUE TITLE
Not drawing some text

### ISSUE THREAD

**Issue by tcurdt** [tdewolff/canvas#30] opened 2020-03-20 23:50 UTC
I am flabbergasted. I stripped down a problem to the following.

This works:

```
  ctx.DrawText(lx, ly, canvas.NewTextLine(face, fmt.Sprintf(
    "XX",
  ), 0))
```

This doesn't draw anything

```
  ctx.DrawText(lx, ly, canvas.NewTextLine(face, fmt.Sprintf(
    "XF",
  ), 0))
```

Any idea?

**Comment by tcurdt** [comment] 2020-03-21 00:02
Some characters create problems. `F` makes all disappear. `y` prints something else.
What on earth is going on?

**Comment by tdewolff** [comment] 2020-03-21 12:48
Not sure, it seems to work fine for me. What font are you using? Does it work with another font? Do you use the latest version of `canvas`? P.s. I don't think that `Sprinf` is needed in this case, but shouldn't really matter either.

**Comment by tcurdt** [comment] 2020-03-21 13:09
`Sprintf` is just a left over. It doesn't really matter. I can also reproduce it without.

I am using `github.com/tdewolff/canvas v0.0.0-20200319222637-d45b6dccc2a3` on macOS 10.15.3 with `go1.14 darwin/amd64`.

    font := canvas.NewFontFamily("Arial")
    // font.Use(canvas.CommonLigatures)
    if err := font.LoadLocalFont("Arial", canvas.FontRegular); err != nil {
      panic(err)
    }
    face := font.Face(16.0, color.Black, canvas.FontRegular, canvas.FontNormal)

but I see the very same behaviour also with

    font := canvas.NewFontFamily("Times")
    // font.Use(canvas.CommonLigatures)
    if err := font.LoadLocalFont("Times New Roman", canvas.FontRegular); err != nil {
      panic(err)
    }

Any thought how to dig deeper? I cannot really make sense of this yet.

**Comment by tcurdt** [comment] 2020-03-21 13:24
Here is a testcase. For me it just prints "Too"

```
package main

import (
	"fmt"
	"image/color"

	"github.com/tdewolff/canvas"
)

func setup() (*canvas.Canvas, *canvas.Context) {

	c := canvas.New(297, 210)
	ctx := canvas.NewContext(c)

	w, h := ctx.Size()

	xmin := float64(-180)
	xmax := float64(+180)
	ymin := float64(-90)
	ymax := float64(+90)

	xscale := w / (xmax - xmin)
	yscale := h / (ymax - ymin)
	_ = xscale
	_ = yscale

	scale := xscale * 0.9

	ctx.SetView(canvas.Identity.
		Translate(w/2, h/2).
		Scale(scale, scale),
	)

	return c, ctx
}

func main() {
	c, ctx := setup()

	h := 8.0

	font := canvas.NewFontFamily("Arial")
	// font.Use(canvas.CommonLigatures)
	if err := font.LoadLocalFont("Arial", canvas.FontRegular); err != nil {
		panic(err)
	}
	face := font.Face(16.0, color.Black, canvas.FontRegular, canvas.FontNormal)

	hx := -180.0
	hy := 90.0 + 2

	ctx.SetFillColor(color.RGBA{0, 0, 0, 255})
	ctx.DrawText(hx, hy, canvas.NewTextLine(face, "Foo", 0))

	ctx.SetFillColor(color.RGBA{0, 0, 0, 255})
	ctx.DrawText(hx+10, hy, canvas.NewTextLine(face, "Too", 0))

	lx := -180.0
	ly := -90.0 - h

	ctx.SetFillColor(color.RGBA{0, 0, 0, 255})
	ctx.DrawText(lx, ly-float64(h*2), canvas.NewTextLine(face, fmt.Sprintf(
		"Fy (%d), year %04d-%04d, month %02d-%02d",
		50,
		2000, 2010,
		1, 12,
	), 0))

	c.SavePDF("out.pdf")
}
```

**Comment by oliverpool** [comment] 2020-03-21 22:09
I can reproduce this with you example.

It seems to be a pdf issue only, since writing the canvas to png does not have this issue:
PDF: [out.pdf](https://github.com/tdewolff/canvas/files/4364303/out.pdf)
PNG: ![out](https://user-images.githubusercontent.com/3864879/77237467-b7d45a80-6bc8-11ea-9048-d8ab9d28495e.png)

`Fy` looks a lot like some PDF command: maybe there is some conflict there.
I also noticed that copy/pasting text from pdfs gives a totally different text (probably not related at all, but who knows...)

**Comment by oliverpool** [comment] 2020-03-21 22:25
The `sfnt.GlyphIndex` of `F` is 41, which gets written as `binary.Write(w, binary.BigEndian, indices)` results in a `)` (which closes the previously opened parenthesis).

https://github.com/tdewolff/canvas/blob/f857c79815ed5f1f4b5c3210f66eefa0af06ac20/pdf.go#L873-L883

Since I am discovering the pdf format with this project, I don't have any idea how this should be fixed :-)

**Comment by oliverpool** [comment] 2020-03-21 22:30
Here is the implementation of gofpdf (which is not maintained anymore - under MIT-License: code could be reused with proper attribution)
https://github.com/jung-kurt/gofpdf/blob/603f56990463f011cb1dbb64ef7f872c1adc009a/fpdf.go#L2432-L2444

**Comment by tcurdt** [comment] 2020-03-21 22:33
Well, it's a good you can reproduce it. That's at least something.

It does not seem to be just `Fy` though. It seems to clash with many other plain english words. Feels like there is something fundamentally broken then :-(

Another implementation that is well maintained is https://github.com/pdfcpu/pdfcpu (Apache License). 
Not sure if that helps.

**Comment by tcurdt** [comment] 2020-03-22 04:29
@oliverpool looking at the code this looks odd

https://github.com/tdewolff/canvas/blob/f857c79815ed5f1f4b5c3210f66eefa0af06ac20/pdf.go#L896

no error gets returned and the call to `write` just gets quietly skipped.
IIUC it's about having always two runes for the kerning.
But what if `GlyphIndex` fails unexpectedly?

**Comment by oliverpool** [comment] 2020-03-22 06:29
> But what if GlyphIndex fails unexpectedly?

Then the `i` is not updated and the whole word will be written later: https://github.com/tdewolff/canvas/blob/f857c79815ed5f1f4b5c3210f66eefa0af06ac20/pdf.go#L907

In your case (at least for the `F`) the `GlyphIndex` does not fail: its encoding as indice is the issue (it gets translated to a `)` which interferes with the pdf encoding)

**Comment by tcurdt** [comment] 2020-03-22 12:23
@oliverpool I don't fully grasp why `val` is not written in one go. There is some kerning information that need to be saved elsewhere? So basically the problem is https://github.com/tdewolff/canvas/blob/f857c79815ed5f1f4b5c3210f66eefa0af06ac20/pdf.go#L880

Which leads to here
https://github.com/tdewolff/canvas/blob/d45b6dccc2a317b1c3e2ecaa3d623030b8b43e2a/font.go#L109

And that's where I am struggling. It looks like the impl is basically writing `( indexFromRune(A) indexFromRune(B) indexFromRune(C) )`.

But looking at the [spec](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf) at 9.2.2. there is an example showing:
![Screen Shot 2020-03-22 at 12 59 13](https://user-images.githubusercontent.com/13697/77248849-03285080-6c3d-11ea-9823-49c5fe9426f9.png)
and this does not seem to be referencing an index at all. Instead it's `( A B C )`.

I assume `indexFromRune()` is something advanced that I just didn't find in the spec yet? I also still haven't found information on quoting, but it seems like hex and octal are supported for every character.

**Comment by oliverpool** [comment] 2020-03-22 13:09
I am not sure, but yes, I guess it is related to kerning.

> this does not seem to be referencing an index at all

It is actually referring to an index. Depending of how the font is stored this index is sometimes the same as the char (`A => A`), but this mapping can differ (here `) => F`).

**I found a fix to your issue and I will try to make a PR soon**

**Comment by tcurdt** [comment] 2020-03-22 14:00
> It is actually referring to an index. Depending of how the font is stored this index is sometimes the same as the char (A => A), but this mapping can differ (here ) => F).

That's what I figured you mean - but I could not find that in the spec yet.
But it is a little surprising that all the fonts I tried had same mapping (and problem) so far though.

You are building quite a suspense with the fix announcement :)

**Comment by tdewolff** [comment] 2020-03-22 16:09
Yes, it seems that `gofpdf` is using some escaping before printing:

```go
func (f *Fpdf) escape(s string) string {
	s = strings.Replace(s, "\\", "\\\\", -1)
	s = strings.Replace(s, "(", "\\(", -1)
	s = strings.Replace(s, ")", "\\)", -1)
	s = strings.Replace(s, "\r", "\\r", -1)
	return s
}
```

That should be added before printing the characters. The way the font is loaded into the PDF makes that we need to use the glyph index instead of the character itself to reference characters. This probably makes copying and pasting text copy the wrong text. This should be fixed with a proper font parser and embedder (haven't gotten around to it yet).

**Comment by tcurdt** [comment] 2020-03-22 16:17
@tdewolff Could the existing `textSubstitution` API used for a work around? Unfortunately it's package only otherwise it would have already tried that.

**Comment by tdewolff** [comment] 2020-03-22 16:22
This seems to work. I wasn't able to add a test yet though.

@oliverpool if you had a better solution I'd be glad to hear it!

**Closed** 2020-03-22 16:21 UTC
