### ISSUE TITLE
move origin to top-left text draw failed

### ISSUE THREAD

**Issue by Modificator** [tdewolff/canvas#139] opened 2021-12-30 03:27 UTC
When I use `SetView(canvas.Identity.ReflectYAbout)` text draw result

![image](https://user-images.githubusercontent.com/3425930/147719193-84e0c34c-72a4-48a0-a6a8-bec8d639be87.png)

use`SetCoordView` can draw right, but other draw can't draw right, ↓ background draw out of canvas

![image](https://user-images.githubusercontent.com/3425930/147719354-fd9ab1e0-207c-41ff-9ec2-faaf75901068.png)

```go
var fontLoadSlice = []string{
	".SF Regular",
	"Arial",
	"Droid Sans",
}
var fontFamily *canvas.FontFamily
	fontFamily = canvas.NewFontFamily("times")
	for _, fontName := range fontLoadSlice {
		err := fontFamily.LoadLocalFont(fontName, canvas.FontRegular)
		fmt.Println(err)
		if err == nil {
			break
		}
	}
	headerFont := fontFamily.Face(28.0, canvas.Black, canvas.FontRegular, canvas.FontNormal)
	c := canvas.New(500, 200)
	ctx := canvas.NewContext(c)
	ctx.SetView(canvas.Identity.ReflectYAbout(100))
        //ctx.SetCoordView(canvas.Identity.ReflectYAbout(100))
	ctx.SetFillColor(canvas.White)
	ctx.DrawPath(0, 0, canvas.Rectangle(c.Size()))
	//ctx.SetStrokeColor(canvas.Black)
	//ctx.DrawPath(10, 10, canvas.Rectangle(480, 180))
	headerText := canvas.NewTextBox(headerFont, "test", 0, 0, canvas.Justify, canvas.Justify, 0, 0)
	ctx.DrawText(30, 30, headerText)
```

**Comment by tdewolff** [comment] 2022-01-03 14:11
Yes, this may not be the easiest for people who'd like to work with top-left as the origin, but `SetCoordView` or `SetCoordSystem` should be used to change the coordinate transformation to position elements (but not transform the elements themselves) while `SetView` transforms the complete view. The former allows you to position the elements with top-left as the origin, but the elements themselves (a path for example) will always have bottom-left (the mathematical standard) as its origin. That is, you define the path with a bottom-left origin, and then you can position it using with top-left as the origin.

I'm thinking of changing this system, by introducing a `CartesianIVContext` for example that draws everything Y-flipped except for text. Additonally, it would be possible to add a `PolarContext` for polar coordinates etc.

**Comment by marco-m** [comment] 2022-05-23 19:50
Is this a duplicate of #72 ?

**Comment by tdewolff** [comment] 2022-05-23 21:07
Yes it is! I will close this one. As mentioned in the other issue:

I've added a change that adds better support for CartesianIV (i.e. origin is top-left). It differs from CartesianI (i.e. origin is bottom-left) in that it anchors differently to images (anchors top-left vs bottom-left) and that text has always been anchored to the baseline (TextLine) or to top-left (TextBox) and remains so. This means that switching to CartesianIV may change the position of text and images.

You can change to CartesianIV using:

```go
ctx.SetCoordSystem(canvas.CartesianIV)
```

**Closed by tdewolff** 2022-05-23 21:07 UTC
